name: publish

on:
  push

jobs:

  publish:

    runs-on: windows-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 7.0.x

      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v1.1.1
        with:
          nuget-version: 5.x
        
      - name: NuGet restore
        run: nuget restore

      - name: .NET restore
        run: dotnet restore

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: MSBuild Build
        run: msbuild -p:Configuration=Release
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Over-Top
          path: OverTop/bin/Release/net7.0-windows

